services:
  gateway:
    build:
      context: ./gateway
    container_name: mini-gateway
    environment:
      PORT: 8080
      REPLICA_URLS: '{"replica1":"http://replica1:5001","replica2":"http://replica2:5002","replica3":"http://replica3:5003"}'
      POLL_INTERVAL_MS: 400
      LEADER_DISCOVERY_MS: 800
    ports:
      - '8080:8080'
    depends_on:
      - replica1
      - replica2
      - replica3
    restart: unless-stopped

  replica1:
    build:
      context: ./replica1
    container_name: replica1
    environment:
      NODE_ID: replica1
      PORT: 5001
      PEERS: '{"replica2":"http://replica2:5002","replica3":"http://replica3:5003"}'
    ports:
      - '5001:5001'
    restart: unless-stopped

  replica2:
    build:
      context: ./replica2
    container_name: replica2
    environment:
      NODE_ID: replica2
      PORT: 5002
      PEERS: '{"replica1":"http://replica1:5001","replica3":"http://replica3:5003"}'
    ports:
      - '5002:5002'
    restart: unless-stopped

  replica3:
    build:
      context: ./replica3
    container_name: replica3
    environment:
      NODE_ID: replica3
      PORT: 5003
      PEERS: '{"replica1":"http://replica1:5001","replica2":"http://replica2:5002"}'
    ports:
      - '5003:5003'
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: mini-frontend
    ports:
      - '3000:80'
    depends_on:
      - gateway
    restart: unless-stopped
